### ISSUE TITLE
The Connect-Range Bug

### ISSUE THREAD

**Issue by Haseebullah9012** [ArmaghanBz/connect_4_game#1]
The game overs without Connecting 4 of them. 
It just looks for the Range of 4 in its surroundings, and if it even one mark in that Range, we Won. 
This is not thw Intention of the Game, i think. :confused:

**Comment by ArmaghanBz** [comment]
you can change the check function as if it is not working. some little changes in an if-else statement can make it work.

**Comment by Haseebullah9012** [comment]
The Issue actually looks for the range of 3 (unlike as mentioned 4 in the Issue), and that itself was a Issue #2. 
This was a Bug, maybe some Conditions were being wrongly executed, but i didn't Found that in the Code. 
But fortunately, with the version 2 of the Game, this Bug is no more. 
The Issue Resolved.
