### ISSUE TITLE
The Goal Bug

### ISSUE THREAD

**Issue by Haseebullah9012** [ArmaghanBz/connect_4_game#2]
The Game's Name is Connect-4. But the inner mentioned Goal is to connect 3. And the Algorithm also checks for consecutive 3. 
This is Strange.

**Comment by ArmaghanBz** [comment]
Thanks for noticing brother. ignore all that stuff, it was my first-year project ( which is a disaster as it looks) but I can tell you that some little render can make it work. you can change the name if you want, but that's how I got it in the first place.

**Comment by Haseebullah9012** [comment]
Yes, i have modified the code. I am just about to push it in the Remote account.

**Comment by Haseebullah9012** [comment]
I updated the Code. 
With the Version 2 of the Game, the Goal is to Connect-4 Consecutive Places (instead of 3). 
So, Issue is Resolved.
